CREATE TABLE IF NOT EXISTS EPICIMAGE (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    identifier VARCHAR(255) NOT NULL,
    caption VARCHAR(255),
    name VARCHAR(255) NOT NULL,
    version VARCHAR(255),
    date TIMESTAMP NOT NULL,
    imageurl VARCHAR(255),
    image BLOB NOT NULL,
    thumbnailurl VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS EPICGIF (
    date DATE PRIMARY KEY,
    data BLOB
);
