CREATE TABLE EPICIMAGE (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    identifier VARCHAR(255) NOT NULL,
    caption VARCHAR(255),
    name VARCHAR(255) NOT NULL,
    version VARCHAR(255),
    date TIMESTAMP NOT NULL,
    url VARCHAR(255),
    image BLOB NOT NULL
);

CREATE TABLE GIF (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    date DATE NOT NULL,
    data BLOB NOT NULL
);
